apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentry-sentry-cron
  labels:
    app: sentry-sentry
    chart: "sentry-2.0.1"
    release: "release-name"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        metrics-enabled: "false"
        checksum/configYml: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/sentryConfPy: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app: sentry-sentry
        release: "release-name"
        role: cron
    spec:
      containers:
      - name: sentry-cron
        image: "sentry:9.1.1"
        imagePullPolicy: IfNotPresent
        args: ["run", "cron"]
        ports:
        - containerPort: 9000
        env:
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentry-sentry
              key: sentry-secret
        - name: SENTRY_DB_USER
          value: "sentry"
        - name: SENTRY_DB_NAME
          value: "sentry"
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-postgresql
              key: postgres-password
        - name: SENTRY_POSTGRES_HOST
          value: sentry-postgresql
        - name: SENTRY_POSTGRES_PORT
          value: "5432"
        - name: SENTRY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-redis
              key: redis-password
        - name: SENTRY_REDIS_HOST
          value: sentry-redis-master
        - name: SENTRY_REDIS_PORT
          value: "6379"
        - name: SENTRY_EMAIL_HOST
          value: "smtp"
        - name: SENTRY_EMAIL_PORT
          value: "25"
        - name: SENTRY_EMAIL_USER
          value: ""
        - name: SENTRY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-sentry
              key: smtp-password
        - name: SENTRY_EMAIL_USE_TLS
          value: "false"
        - name: SENTRY_SERVER_EMAIL
          value: "sentry@sentry.local"
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: /var/lib/sentry/files
          name: sentry-data
        resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi

      volumes:
      - name: config
        configMap:
          name: sentry-sentry
      - name: sentry-data
        emptyDir: {}
