apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "sentry"
  labels:
    app.kubernetes.io/name: "sentry"
    app.kubernetes.io/version: "9.1.1"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "sentry"
  componentKinds:
    - group: core
      kind: Service
    # I have no idea what I'm doing here.
    - group: core
      kind: Ingress
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
  descriptor:
    version: "9.1.1"
    description: "Open-source error tracking with full stacktraces & asynchronous context."
    type: "sentry"
    links:
      - description: Open Sentry Enterprise
        url: "http://sentry"